- name: Demo on variables
  hosts: all
  vars:
    URL: play.example.com
  tasks:
    - name: Print URL
      ansible.builtin.debug:
        msg: URL = {{ URL }}



- name: Demo file variable
  hosts: all
  vars_files:
    - sample-vars.yml
  tasks:
    - name: Print URL
      ansible.builtin.debug:
        msg: URL = {{ URL }}


- name: Demo on Task variable
  hosts: all
  tasks:
    - name: Print URL
      ansible.builtin.debug:
        msg: URL = {{ URL }}

      vars:
        URL: task.example.com

- name: print fact
  hosts: all
  tasks:
    - name: print hostname
      ansible.builtin.debug:
        msg: Hostname = {{ ansible_hostname }}

- name: Demo on Inventory variable
  hosts: all
  tasks:
    - name: Print URL
      ansible.builtin.debug:
        msg: URL = {{ URL }}


- name: Register a variable example
  hosts: all
  tasks:
    - name: Get uptime
      ansible.builtin.shell: uptime
      register: out

    - name: Print out register
      ansible.builtin.debug:
        msg: "{{out}}"









